version: '3'

services:
  redmine:
    restart: always
    build: redmine
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_ENCODING: utf8mb4
      REDMINE_PLUGINS_MIGRATE: 1
    depends_on:
      - db
      - plugins
      - themes
    volumes:
      - plugins:/usr/src/redmine/plugins
      - themes:/usr/src/redmine/public/themes/minimalflat2

  db:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine

  plugins:
    build: plugins
    volumes:
      - plugins:/usr/src/redmine/plugins

  themes:
    build: themes
    volumes:
      - themes:/usr/src/redmine/public/themes/minimalflat2

volumes:
  plugins:
  themes:
